server:
  port: 8092

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
        
        
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # do not use localhost :)
          jwk-set-uri: http://machine.local:8090/oauth2/jwks
        